/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MjcAmbulanceWlList {
    }
}
declare global {
    interface HTMLMjcAmbulanceWlListElement extends Components.MjcAmbulanceWlList, HTMLStencilElement {
    }
    var HTMLMjcAmbulanceWlListElement: {
        prototype: HTMLMjcAmbulanceWlListElement;
        new (): HTMLMjcAmbulanceWlListElement;
    };
    interface HTMLElementTagNameMap {
        "mjc-ambulance-wl-list": HTMLMjcAmbulanceWlListElement;
    }
}
declare namespace LocalJSX {
    interface MjcAmbulanceWlList {
    }
    interface IntrinsicElements {
        "mjc-ambulance-wl-list": MjcAmbulanceWlList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "mjc-ambulance-wl-list": LocalJSX.MjcAmbulanceWlList & JSXBase.HTMLAttributes<HTMLMjcAmbulanceWlListElement>;
        }
    }
}
